Feature #8 add state machine to task
pavels3579/TaskManager pull request #7
Opened 2021-12-07 07:52 UTC by pavels3579

2021-12-07 08:53 UTC, moklidia requested changes

2021-12-07 08:53 UTC, moklidia commented on app/models/task.rb
> +    event :for_release do
Давай назовем события так, чтобы в них содержалось действия, т.е. через глаголы

2021-12-07 09:11 UTC, pavels3579 commented on app/models/task.rb
> +    event :for_release do
Исправил.

2021-12-09 07:14 UTC, greybutton approved these changes

2021-12-09 08:04 UTC, merged